# Generated by Django 4.2.6 on 2023-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='teaching_type',
            field=models.CharField(choices=[('HOD', 'Hod'), ('P', 'Professor'), ('AP', 'Assistant Professor'), ('LS', 'Lab Staff')], default=None, max_length=3, verbose_name='Teaching Type'),
        ),
    ]
