# Generated by Django 4.2.6 on 2023-10-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='teaching_type',
            field=models.CharField(blank=True, choices=[('HOD', 'Hod'), ('P', 'Professor'), (
                'AP', 'Assistant Professor'), ('LS', 'Lab Staff')], max_length=3, null=True, verbose_name='Teaching Type'),
        ),
    ]
