# Generated by Django 4.2.6 on 2023-10-11 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(default=None, max_length=5, verbose_name='Degree')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_type', models.CharField(choices=[('HOD', 'Hod'), ('P', 'Professor'), ('AP', 'Assistant Professor'), ('LS', 'Lab Staff')], default=None, max_length=3, verbose_name='TeachingType')),
                ('contact_information', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('roles', models.ManyToManyField(to='staff.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_Type', models.CharField(max_length=20, verbose_name='Teaching Type')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Training Name')),
                ('request_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], max_length=1, verbose_name='Request Status')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=20, verbose_name='Branch')),
                ('instituition', models.CharField(max_length=150, verbose_name='Instituition')),
                ('year_passing', models.CharField(help_text='eg: 2020-2024', max_length=9, verbose_name='Year Passing')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.degree')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PerfromanceEvulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsetting', models.TextField(max_length=100, verbose_name='Goals')),
                ('assessments', models.TextField(max_length=100, verbose_name='Assessments')),
                ('feedback', models.TextField(max_length=200, verbose_name='Feedback')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Strart Date')),
                ('end_date', models.DateField(verbose_name='end Date')),
                ('reason', models.TextField(max_length=200, verbose_name='Reason')),
                ('leave_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1, verbose_name='Leave Status')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('relationship', models.CharField(max_length=30, verbose_name='Relationship')),
                ('phone', models.CharField(max_length=15, verbose_name='Phonenumber')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, verbose_name='Day')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.academicprogram')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
