# Generated by Django 4.2.6 on 2023-10-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_training_request_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingType',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='roles',
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Un Married', 'Un Married')], default='Married', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='nationality',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='religion',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='teaching_type',
            field=models.CharField(choices=[('HOD', 'Hod'), ('P', 'Professor'), ('AP', 'Assistant Professor'), ('LS', 'Lab Staff')], default=None, max_length=3, verbose_name='Teaching Type'),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
