# Generated by Django 4.2.6 on 2023-10-12 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_delete_teachingtype_remove_staff_roles_staff_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 10, 28, 5, 248950)),
            preserve_default=False,
        ),
    ]
