# Generated by Django 4.2.6 on 2023-10-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_experience_staff_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='contact_information',
            new_name='contact_numbrer',
        ),
    ]
