# Generated by Django 4.2.6 on 2023-10-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_rename_contact_information_staff_contact_numbrer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='contact_numbrer',
            new_name='contact_number',
        ),
    ]
