# Generated by Django 4.2.6 on 2023-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email_id',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Id'),
        ),
    ]
