# Generated by Django 4.2.6 on 2023-10-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_staff_email_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='qualifications',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Qualifications'),
        ),
    ]
