# Generated by Django 4.2.6 on 2023-10-11 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.IntegerField(verbose_name='Basic Salary')),
                ('allowances', models.IntegerField(default=0, verbose_name='Allowance')),
                ('deductions', models.IntegerField(default=0, verbose_name='Deduction')),
                ('final_salary', models.IntegerField(default=0, verbose_name='Final Salary')),
                ('generated_at', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'verbose_name': 'Salary',
                'verbose_name_plural': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Month')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.salary')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to='payroll.salary')),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_allowances', to='payroll.salary')),
            ],
        ),
    ]
