# Generated by Django 4.2.6 on 2023-10-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
