# Generated by Django 4.2.6 on 2023-10-11 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('tenth_mark', models.CharField(max_length=3, verbose_name='10th')),
                ('twelveth_mark', models.CharField(max_length=3, verbose_name='12th')),
                ('contact_number', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=30)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('user_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('document', models.FileField(upload_to='student_documents/', verbose_name='Document')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Perfromance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marks')),
                ('grade', models.CharField(choices=[('o', 'o'), ('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B')], max_length=5, verbose_name='Grade')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('exam_date', models.DateField()),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name='Teacher Feedback')),
                ('project_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Project Score')),
                ('participation_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Participation  Level')),
                ('additional_comments', models.TextField(blank=True, null=True, verbose_name='Additional Comments')),
                ('test_1_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=' Test 1 Score')),
                ('test_2_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Test 2 Score')),
                ('final_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Final Exam Score')),
                ('practical_exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prartical Exam Score')),
                ('assignment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Assignment Score')),
                ('presentation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Presentation Score')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Strart Date')),
                ('end_date', models.DateField(verbose_name='end Date')),
                ('reason', models.TextField(max_length=200, verbose_name='Reason')),
                ('leave_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1, verbose_name='Leave Status')),
                ('student_leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, verbose_name='Day')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('academic_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.academicprogram')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.classroom')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default=None, max_length=10)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('student_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Marks')),
                ('grade', models.CharField(max_length=5, verbose_name='Grade')),
                ('teacher_comments', models.TextField(blank=True, null=True, verbose_name='Teacher Comments')),
                ('year', models.CharField(max_length=4, verbose_name='year')),
                ('subject_code', models.CharField(max_length=10, verbose_name='Subject Code')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Attendance Precentage')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.classroom')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
